# Generated by Django 2.0.2 on 2018-09-04 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='real_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='real_title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
