# Generated by Django 2.1.1 on 2018-11-28 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_auto_20180904_2118'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FailedConsultation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MissingSong',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fbid', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='artist',
            name='real_name',
        ),
        migrations.RemoveField(
            model_name='song',
            name='real_title',
        ),
        migrations.AddField(
            model_name='artist',
            name='hits',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='artist',
            name='number_of_songs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='artist',
            name='songs_url',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='url',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='hits',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='song',
            name='url',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='failedconsultation',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.MissingSong'),
        ),
        migrations.AddField(
            model_name='failedconsultation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.User'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.Song'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.User'),
        ),
    ]
